# Generated by Django 2.2.10 on 2020-05-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('studygroups', '0001_initial'), ('studygroups', '0002_studygroup_name'), ('studygroups', '0003_auto_20150324_0450')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('provider', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=128)),
                ('prerequisite', models.TextField()),
                ('time_required', models.CharField(max_length=128)),
                ('caption', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('location_link', models.URLField()),
                ('time', models.CharField(max_length=128)),
                ('max_size', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.Course')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroupSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.StudyGroup')),
            ],
            options={
                'unique_together': {('email', 'study_group')},
            },
        ),
    ]
