# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 13:14


from django.db import migrations

def rewrite_mobile_numbers(apps, schema_editor):
    Application = apps.get_model("studygroups", "Application")
    for apl in Application.objects.exclude(mobile=''):
        if apl.mobile.startswith('07'):
            # rewrite kenyan numbers currently in database 
            apl.mobile = '+254' + apl.mobile.replace('-', '')[1:]
        else:
            # other numbers are assumed to be US numbers
            apl.mobile = '+1' + apl.mobile.replace('-', '')
        apl.save()

class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0065_team_teammembership'),
    ]

    operations = [
        migrations.RunPython(rewrite_mobile_numbers),
    ]
