# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 13:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0066_rewrite_mobile_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='page_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='team',
            name='page_slug',
            field=models.SlugField(blank=True, max_length=256),
        ),
    ]
