# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 09:45


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0070_lowercase_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='signup_questions',
            field=models.TextField(default=b'{}'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.Course'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='duration',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='venue_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='venue_details',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='venue_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='venue_website',
            field=models.URLField(blank=True),
        ),
    ]
