# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 09:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0071_auto_20170518_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
