# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0075_auto_20170823_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='on_demand',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.CharField(max_length=500),
        ),
    ]
