# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0077_course_unlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='sms_body',
            field=models.CharField(blank=True, max_length=160, verbose_name='SMS (Text)'),
        ),
    ]
