# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0079_studygroup_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
