# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 08:17
from __future__ import unicode_literals

from django.db import migrations

def set_draft_false(apps, schema_editor):
    """ make sure all studygroups are publised prior to introduction of the draft feature. 
    """
    StudyGroup = apps.get_model("studygroups", "StudyGroup")
    for study_group in StudyGroup.objects.all():
        study_group.draft = False
        study_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0080_facilitator_email_confirmed_at'),
    ]

    operations = [
        migrations.RunPython(set_draft_false),
    ]
