# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 12:11
from __future__ import unicode_literals

from django.db import migrations


def init_email_confirmed_at(apps, schema_editor):
    Facilitator = apps.get_model("studygroups", "Facilitator")
    for facilitator in Facilitator.objects.filter(user__last_login__isnull=False):
        facilitator.email_confirmed_at = facilitator.user.last_login
        facilitator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0081_set_existing_studygroups_draft_to_false'),
    ]

    operations = [
        migrations.RunPython(init_email_confirmed_at),
    ]
