# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0082_init_email_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='facilitator_concerns',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='facilitator_goal',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='signup_question',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
