# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0083_auto_20180209_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facilitator',
            new_name='Profile',
        ),
    ]
