# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0085_studygroup_place_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyGroupMeeting',
            new_name='Meeting',
        ),
    ]
