# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 09:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0086_auto_20180220_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
