# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0087_auto_20180221_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='goal_met',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='card',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='index',
            field=models.PositiveIntegerField(help_text='meeting index this activity corresponds to'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='signup_questions',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('5', 'Great'), ('4', 'Pretty well'), ('3', 'Good'), ('2', 'Not so great'), ('1', 'I need some help')], max_length=16),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='page_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('MEMBER', 'Member')], max_length=256),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('MEMBER', 'Member')], max_length=256),
        ),
    ]
