# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0088_auto_20180316_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
