# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0092_course_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mobile_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
