# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-04 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0097_profile_reason_for_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reason_for_registration',
        ),
    ]
