# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0098_remove_profile_reason_for_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='communications_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in_learning',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
