# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0099_auto_20180909_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='communications_opt_in',
        ),
        migrations.AddField(
            model_name='profile',
            name='communication_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
