# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0100_auto_20180909_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='region',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
