# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-11 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0100_auto_20180909_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='communication_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
