# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-14 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0105_fix_communications_opt_in_true_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='country_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
