# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0106_studygroup_country_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='country_en',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
