# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0107_auto_20181115_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interested_in_learning',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
