# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0109_auto_20190308_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overall_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
