# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-20 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0112_application_communications_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='language',
            field=models.CharField(default='en', max_length=6),
            preserve_default=False,
        ),
    ]
