# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-02 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0113_studygroup_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='zoom',
            field=models.IntegerField(default=7),
        ),
    ]
