# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0115_team_created_at_squashed_0123_auto_20190715_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
