# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-10 14:09
from __future__ import unicode_literals

from django.db import migrations, models


def set_null_values(apps, schema_editor):
    Course =  apps.get_model("studygroups", "Course")
    Course.objects.filter(total_ratings__isnull=True).update(total_ratings=0)
    Course.objects.filter(total_reviewers__isnull=True).update(total_reviewers=0)


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0116_auto_20190722_2014'),
    ]

    operations = [
        migrations.RunPython(set_null_values),
    ]
