# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-10 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0117_auto_20190910_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_ratings',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_reviewers',
            field=models.SmallIntegerField(default=0),
        ),
    ]
