# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0115_team_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
