# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-25 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0118_auto_20190910_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='caption',
            field=models.CharField(max_length=500),
        ),
    ]
