# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-30 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0119_auto_20191025_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
