# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-08 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0120_auto_20190618_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invitation_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='communication_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
