# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-09 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0120_course_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tagdorsement_counts',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tagdorsements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_reviewers',
        ),
    ]
