# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0121_auto_20190708_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='communication_opt_in',
        ),
        migrations.AddField(
            model_name='teammembership',
            name='weekly_update_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
