# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0121_auto_20191209_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='facilitator_goal_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
