# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-16 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0122_studygroup_facilitator_goal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='did_not_happen',
            field=models.NullBooleanField(),
        ),
    ]
