# Generated by Django 2.2.10 on 2020-04-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0124_auto_20200419_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
