# Generated by Django 2.2.10 on 2020-05-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0125_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='course_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
