# Generated by Django 2.2.10 on 2020-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0126_studygroup_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
