# Generated by Django 2.2.10 on 2020-06-09 21:38

from django.db import migrations


def update_study_group_name(apps, schema_editor):
    StudyGroup = apps.get_model("studygroups", "StudyGroup")
    for sg in StudyGroup.objects.all():
        sg.name = sg.course.title[:128]
        sg.course_description = sg.course.caption
        sg.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0128_auto_20200525_1426'),
    ]

    operations = [
        migrations.RunPython(update_study_group_name),
    ]
