# Generated by Django 2.2.13 on 2020-06-23 19:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0129_set_learning_circle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='intro_text',
            field=tinymce.models.HTMLField(blank=True, max_length=500),
        ),
    ]
