# Generated by Django 2.2.13 on 2020-07-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0131_auto_20200703_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='duration',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
