# Generated by Django 2.2.13 on 2020-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0132_auto_20200710_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('link_text', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('yellow', 'Yellow')], default='orange', max_length=6)),
            ],
        ),
    ]
