# Generated by Django 2.2.13 on 2020-07-26 15:16

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0133_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='last_meeting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='intro_text',
            field=django_bleach.models.BleachField(blank=True, max_length=1000),
        ),
    ]
