# Generated by Django 2.2.13 on 2020-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0134_auto_20200723_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='venue_website',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
