# Generated by Django 2.2.13 on 2020-07-26 15:17

from django.db import migrations

def set_last_meeting_date(apps, schema_editor):
  StudyGroup = apps.get_model('studygroups', 'StudyGroup')
  published = StudyGroup.objects.filter(deleted_at__isnull=True, draft=False)

  for sg in published:
      last_meeting = sg.meeting_set.filter(deleted_at__isnull=True).order_by('-meeting_date', '-meeting_time').first()
      if last_meeting is not None:
          sg.last_meeting_date = last_meeting.meeting_date
          sg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0134_auto_20200726_1516'),
    ]

    operations = [
      migrations.RunPython(set_last_meeting_date),
    ]
