# Generated by Django 2.2.13 on 2020-08-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0134_auto_20200723_0430'),
        ('studygroups', '0135_auto_20200726_1517'),
    ]

    operations = [
    ]
