# Generated by Django 2.2.13 on 2020-09-02 12:24

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0135_auto_20200828_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='course_description',
            field=django_bleach.models.BleachField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='description',
            field=django_bleach.models.BleachField(blank=True, max_length=2000),
        ),
    ]
