# Generated by Django 2.2.13 on 2020-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0136_auto_20200902_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='meeting_frequency',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
