# Generated by Django 2.2.13 on 2020-11-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0137_studygroup_meets_weekly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='meets_weekly',
        ),
    ]
