# Generated by Django 2.2.13 on 2020-11-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0138_remove_studygroup_meets_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='subtitle',
            field=models.CharField(default='Join your neighbors at the library to learn something together. Learning circles meet weekly in person for 6-8 weeks, and are free to join.', max_length=256),
            preserve_default=False,
        ),
    ]
