# Generated by Django 2.2.13 on 2021-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0141_studygroup_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reflection',
            field=models.TextField(blank=True),
        ),
    ]
