# Generated by Django 2.2.13 on 2021-02-15 13:38

from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0142_auto_20210210_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studygroups.Reminder'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='follow_up_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_body',
            field=django_bleach.models.BleachField(max_length=4000),
        ),
    ]
