# Generated by Django 2.2.13 on 2021-04-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0143_auto_20210215_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', 'Great'), ('4', 'Pretty well'), ('3', 'Good'), ('2', 'Not so great'), ('1', 'I need some help')], max_length=16),
        ),
    ]
