# Generated by Django 2.2.13 on 2021-04-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0144_auto_20210413_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='wrapup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
