# Generated by Django 2.2.13 on 2021-05-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0145_meeting_wrapup_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='follow_up',
            new_name='recap',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='follow_up_dismissed',
            new_name='recap_dismissed',
        ),
    ]
