# Generated by Django 2.2.13 on 2021-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0146_auto_20210507_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='facilitator_survey_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
