# Generated by Django 2.2.13 on 2021-05-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0147_studygroup_facilitator_survey_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='course_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='course_rating_reason',
            field=models.TextField(blank=True),
        ),
    ]
