# Generated by Django 2.2.13 on 2021-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0149_update_feedback_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='learner_survey_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', 'Great'), ('4', 'Pretty well'), ('3', 'Okay'), ('2', 'Not so good'), ('1', 'Awful')], max_length=16),
        ),
    ]
