# Generated by Django 2.2.13 on 2021-06-11 13:59

from django.db import migrations
from django.db.models import F

from django.utils import timezone

def set_learner_survey_sent_at(apps, schema_editor):
    StudyGroup = apps.get_model('studygroups', 'StudyGroup')
    StudyGroup.objects.filter(end_date__lt=timezone.now()).update(learner_survey_sent_at=F('end_date'))

class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0150_auto_20210611_1346'),
    ]

    operations = [
        migrations.RunPython(set_learner_survey_sent_at),
    ]
