# Generated by Django 2.2.24 on 2021-11-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0153_team_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studygroups.Team'),
        ),
    ]
