# Generated by Django 2.2.24 on 2022-02-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0156_facilitatorguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatorguide',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studygroups.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='facilitatorguide',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
