# Generated by Django 2.2.24 on 2022-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0157_auto_20220204_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='cu_credit',
            field=models.BooleanField(default=False, verbose_name='Learning circle is eligible for credit from CU'),
        ),
    ]
