# Generated by Django 2.2.24 on 2022-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0158_studygroup_cu_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='cu_credit',
            field=models.BooleanField(default=False, help_text='Learning circle is eligible for credit from CU', verbose_name='CU credit?'),
        ),
    ]
