# Generated by Django 3.2.13 on 2022-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0159_auto_20220510_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='unlisted',
            new_name='members_only',
        ),
    ]
