# Generated by Django 3.2.13 on 2022-06-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0160_rename_unlisted_studygroup_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='edited_by_facilitator',
            field=models.BooleanField(default=False),
        ),
    ]
