# Generated by Django 3.2.13 on 2022-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0161_reminder_edited_by_facilitator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='did_not_happen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='joined',
            field=models.BooleanField(null=True),
        ),
    ]
