# Generated by Django 3.2.13 on 2022-07-12 13:32

from django.db import migrations

def create_facilitator_entries(apps, schema_editor):
    StudyGroup = apps.get_model('studygroups', 'StudyGroup')
    Facilitator = apps.get_model('studygroups', 'Facilitator')

    for sg in StudyGroup.objects.all():
        f = Facilitator.objects.create(study_group=sg, user=sg.facilitator)
        Facilitator.objects.filter(pk=f.pk).update(added_at=sg.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0163_facilitator'),
    ]

    operations = [
        migrations.RunPython(create_facilitator_entries),
    ]
