# Generated by Django 3.2.13 on 2022-08-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0165_rename_facilitator_studygroup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resource_format',
            field=models.CharField(choices=[('course', 'Online Course'), ('book', 'Book'), ('video', 'Video'), ('article', 'Article'), ('group', 'Interest Group')], default='course', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='topics_curated',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='license',
            field=models.CharField(default='Not sure', max_length=128),
        ),
    ]
