# Generated by Django 3.2.13 on 2022-09-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0165_rename_facilitator_studygroup_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='resource_format',
            field=models.CharField(choices=[('course', 'Online Course'), ('book', 'Book'), ('video', 'Video'), ('article', 'Article'), ('group', 'Interest Group')], default='course', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='license',
            field=models.CharField(default='Not sure', max_length=128),
        ),
        migrations.AddField(
            model_name='course',
            name='topic_guides',
            field=models.ManyToManyField(to='studygroups.TopicGuide'),
        ),
    ]
