# Generated by Django 3.2.13 on 2022-09-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0168_alter_course_on_demand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='topics',
            new_name='keywords',
        ),
    ]
