# Generated by Django 3.2.13 on 2022-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0168_alter_course_on_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
