# Generated by Django 3.2.13 on 2022-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0169_rename_topics_course_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicguide',
            name='slug',
            field=models.SlugField(default='not-set', max_length=64),
            preserve_default=False,
        ),
    ]
