# Generated by Django 4.2.11 on 2025-07-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0171_courselist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic_guides',
            field=models.ManyToManyField(blank=True, to='studygroups.topicguide'),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='courses',
            field=models.ManyToManyField(blank=True, to='studygroups.course'),
        ),
    ]
