# Generated by Django 4.2.11 on 2025-11-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('studygroups', '0172_alter_course_topic_guides_alter_courselist_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='course_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
