# Generated by Django 4.2.11 on 2026-01-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('studygroups', '0173_studygroup_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
