# Generated by Django 4.2.11 on 2026-01-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0172_studygroup_signup_limit_alter_course_topic_guides_and_more'),
        ('studygroups', '0174_course_course_content'),
    ]

    operations = [
    ]
