# Generated by Django 4.2.11 on 2026-01-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_cohortcomment_cohort_and_more'),
        ('studygroups', '0176_alter_studygroup_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
