# Generated by Django 4.2.11 on 2026-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0177_alter_course_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='granular_attendance',
            field=models.JSONField(default=dict),
        ),
    ]
