# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-23 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('timezone', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('region', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('country_en', models.CharField(blank=True, max_length=256)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
