# Generated by Django 3.2.13 on 2022-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_calendar', '0003_auto_20200302_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='moderation_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
