# Generated by Django 3.2.15 on 2022-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='geonameid',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
