# Generated by Django 4.2.11 on 2025-07-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('ROLLING', 'Rolling'), ('FIXED', 'Fixed')], max_length=32)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('signup', models.CharField(choices=[('OPEN', 'Anyone can sign up'), ('MODERATED', 'Signups are moderated'), ('CLOSED', 'Signups are closed')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=32)),
                ('image_uri', models.CharField(max_length=256)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('creator_uri', models.CharField(max_length=256)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_courses', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_uri', models.CharField(max_length=256)),
                ('index', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CohortSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uri', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('LEARNER', 'Learner'), ('ORGANIZER', 'Organizer')], max_length=10)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_set', to='courses.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='CohortComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_uri', models.CharField(max_length=256)),
                ('reference_uri', models.CharField(max_length=256)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='courses.cohort')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_set', to='courses.course'),
        ),
    ]
