# Generated by Django 4.2.11 on 2026-01-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortcomment',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='cohortsignup',
            name='cohort',
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
        migrations.DeleteModel(
            name='CohortComment',
        ),
        migrations.DeleteModel(
            name='CohortSignup',
        ),
    ]
