# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_learnersurveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorsurveyresponse',
            name='form_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='learnersurveyresponse',
            name='form_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
