# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-19 10:33
from __future__ import unicode_literals

from django.db import migrations
import json


def set_form_ids(apps, schema_editor):
    LearnerSurveyResponse = apps.get_model("surveys", "LearnerSurveyResponse")
    for resp in LearnerSurveyResponse.objects.all():
        survey = json.loads(resp.survey)
        resp.form_id = survey.get('id')
        resp.save()

    FacilitatorSurveyResponse = apps.get_model("surveys", "FacilitatorSurveyResponse")
    for resp in FacilitatorSurveyResponse.objects.all():
        survey = json.loads(resp.survey)
        resp.form_id = survey.get('id')
        resp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20191219_1032'),
    ]

    operations = [
        migrations.RunPython(set_form_ids),
    ]
