# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-19 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_set_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatorsurveyresponse',
            name='form_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='learnersurveyresponse',
            name='form_id',
            field=models.CharField(max_length=12),
        ),
    ]
