# Generated by Django 2.2.10 on 2020-03-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20191219_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatorsurveyresponse',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studygroups.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='learnersurveyresponse',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studygroups.Application'),
        ),
        migrations.AlterField(
            model_name='learnersurveyresponse',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studygroups.StudyGroup'),
        ),
    ]
