# Generated by Django 2.2 on 2019-04-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='uploads/images')),
                ('uploader_uri', models.CharField(max_length=256)),
            ],
        ),
    ]
